spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:ppiapp}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate.default_schema: SECURITY
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.show_sql: true
      hibernate.format_sql: true
  sql:
    init:
      platform: org.hibernate.dialect.PostgreSQL95Dialect

server:
  port: ${PORT:8001}
  servlet:
    context-path: "/api"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2